### ISSUE TITLE
Entering mouse ID in experiment data entry

### ISSUE THREAD

**Issue by lmcallan** [BridgesLab/mousedb#15]
when entering date for experiment in it no longer allows you to type in mouse ID number but instead give you a drop down menu of all the mice in the database. You basically have to search though all the mice in the list looking for the one you want (time consuming). also it means you cant add data for already dead mice, as they don't appear on the list.

**Comment by davebridges** [comment]
I had to put in a ticket with UM IT to install the django-ajax-selects module.  Will fix this after this is installed.
